replicaCount: 1

image:
  repository: 471112853004.dkr.ecr.ap-northeast-2.amazonaws.com 
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: 50Mi
    cpu: 100m
  limits:
    memory: 50Mi
    cpu: 100m

service:
  type: NodePort
  port: 80

hpa:
  enabled: true
  minReplicas: 6
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

apps:
  - name: web-intro
    imageTag: 23
